### ISSUE TITLE
Error running walletconnect

### ISSUE THREAD

**Issue by jack3689** [WalletConnect/walletconnect-example-dapp#100]
I used WalletConnect-example-dapp to integrate walletconnect in my project, but failed to run. The code runs to `new WalletConnect({ bridge, qrcodeModal: QRCodeModal });`, error reported.
First, it throw the error.
![1666342221174](https://user-images.githubusercontent.com/101615181/197154820-b23ab80a-b8f5-43ec-a33b-1cf658315829.png)
Then I add the code in my code.
```
import {Buffer} from "buffer"
window.Buffer = Buffer;
```
It throw another error.
![image](https://user-images.githubusercontent.com/101615181/197155316-2a1c99b1-9686-45e0-9ed1-f1100f4dd465.png)

This is the method(`Buffer.from`) in walletconnect-example-dapp(`@types/node/globals.d.ts`)
`static from(arrayBuffer: ArrayBuffer | SharedArrayBuffer, byteOffset?: number, length?: number): Buffer;`
This is mine(`@types/node/buffer.d.ts`)
`from(arrayBuffer: WithImplicitCoercion<ArrayBuffer | SharedArrayBuffer>, byteOffset?: number, length?: number): Buffer;`

Who can help me? Thanks very much!

**Comment by shopnb1** [comment]
How to solve the problem?
