### ISSUE TITLE
Is the Demo Working?

### ISSUE THREAD

**Issue by digitaldonkey** [WalletConnect/walletconnect-example-dapp#2]
There is actually no (easily accessible?) information provided about what to do with the QR code popping up after starting the demo. 

What wallets are supported? What I should scan with? What should happen?

**Comment by digitaldonkey** [comment]
Seems that the Demo is broken. On balance (manager.balance.io) I got it working with WallEth. But the demo just says 

![image](https://user-images.githubusercontent.com/444718/45883249-cada5480-bdb0-11e8-8764-330b1c7ac0f2.png)

**Comment by ligi** [comment]
The encoding in the QR code seems to be off - that said great to see that a test-dapp with 1328 is on the way ;-)

**Comment by digitaldonkey** [comment]
Also applies to https://example.walletconnect.org/

**Comment by pedrouid** [comment]
Here is the code for the URI parsing: https://github.com/WalletConnect/eth-parse-uri/blob/master/src/index.js
It matches the ERC 1328 spec, let me know what's the issue on Walleth side @ligi

**Comment by ligi** [comment]
The encoding is wrong here - this way we will not get the android intent system. e.g. the colon after ethereum must not be url encoded. But there is also a problem on the WallETH end so your bug gives me some time to fix my side ;-)
Anyway nice to see that there is a example dapp to test with now - this was really missing - much appreciated!

**Comment by pedrouid** [comment]
The URI now should look like something like this now:
```
ethereum:wc-f4f4321e-3651-4455-8b21-5661dec65f72@1?name=Example%20Dapp&bridge=https%3A%2F%2Fbridge.walletconnect.org&symKey=4FxVSHI82G9TlU37O+2CG3bLFb4ZEA2OPIdpBxdT/+Y=
```
Thanks for bringing it up @digitaldonkey, the `walletconnect-developer-app` it's currently a work-in-progress but both Balance and Walleth should be pushing updates for WalletConnect v0.6.x very soon

**Comment by ligi** [comment]
when will this fix hit: https://example.walletconnect.org ? I also tried to run it locally and the : is working there - but somehow it does not poll - so the QR-Code never vanishes:

![image](https://user-images.githubusercontent.com/111600/45900965-95019400-bde1-11e8-9ef5-3353614a527c.png)

**Comment by pedrouid** [comment]
Yes I noticed that, I'm debugging it. The QR code is formatted correctly, it's the short polling that it's not resolving

**Comment by digitaldonkey** [comment]
Test update: Now there are 3 different options, bot non works or makes sense. 

![image](https://user-images.githubusercontent.com/444718/45967314-e43c0480-c02d-11e8-812b-833c25aa7e0b.png)
