### ISSUE TITLE
Test Bridge error

### ISSUE THREAD

**Issue by NoahZinsmeister** [WalletConnect/walletconnect-example-dapp#28]
FYI @pedrouid, getting a `net::ERR_CERT_DATE_INVALID` error when using the test bridge, you can check it out yourself by going to https://example.walletconnect.org/ and checking the console.

**Comment by pedrouid** [comment]
Thanks @NoahZinsmeister for reporting this! The `test-bridge.walletconnect.org` SSL certificate had expired. It's working now! 👍
