### ISSUE TITLE
Layout issue on firefox

### ISSUE THREAD

**Issue by ligi** [WalletConnect/walletconnect-example-dapp#36]
![image](https://user-images.githubusercontent.com/111600/55631072-77ad7980-57b7-11e9-9fed-2ca5f3822a9b.png)

**Comment by pedrouid** [comment]
Damn that looks ugly, need to take a look at the text-wrapping on Firefox

**Comment by digitaldonkey** [comment]
Better leave the Modal entirely out of your code and only provide it at the example level.

**Comment by pedrouid** [comment]
This is not the `@walletconnect/qrcode-modal` modal but the example's own modal

**Comment by pedrouid** [comment]
Finally fixed this 😂
