### ISSUE TITLE
Wallet connect doesn't connect to binance wallet

### ISSUE THREAD

**Issue by ankitamadan** [WalletConnect/walletconnect-example-dapp#47]
Walletconnect on scanning says `no accounts available`. See below 

![IMG_7793](https://user-images.githubusercontent.com/4128560/76496799-e433fc80-648d-11ea-9ed8-d966c6cea5f0.PNG)

Although I have accounts available. See below

![Image from iOS (1)](https://user-images.githubusercontent.com/4128560/76496905-15143180-648e-11ea-8c1a-171c60eab7f1.png)

**Comment by pedrouid** [comment]
This example only supports Ethereum for now
