### ISSUE TITLE
Signing Transaction not creating request in client

### ISSUE THREAD

**Issue by saitejach127** [WalletConnect/walletconnect-example-dapp#53]
The signing of Transaction is not creating confirm or reject request in the mobile client.
Sign in using QR code is working 
We are using quorum as our RPC.
Initialising of connector works but signing doesnt work
Whereas in send transaction it creates an unknown error of Error : [object Object]

All information with code can be found at this gist
https://gist.github.com/saitejach127/9794f4d3622bd65bd9d14f14ba1a93ff

**Comment by tmem1438** [comment]
Help me with the steps, I am a beginner, many currencies here, I do not
know how to take it out and I am grateful and appreciative of you

في جمعة، 3 يوليو، 2020 في 9:49 ص، كتب SaiTeja22 <notifications@github.com>:

**Comment by tmem1438** [comment]
I entered the link, how is the treatment, please help

في جمعة، 3 يوليو، 2020 في 9:49 ص، كتب SaiTeja22 <notifications@github.com>:
