### ISSUE TITLE
Scan - application title/description

### ISSUE THREAD

**Issue by lgushijima** [WalletConnect/walletconnect-example-dapp#60]
Hey guys, I'm creating a desktop app using electron, and I'm using this @walletconnect/client package...
I can render the qrCode and everything looks pretty much working, but when I scan it using my Trust wallet, it shows only this "Connect to:  file://"

how can I set my application name/description to this?

const connector = new WalletConnect({
bridge: "https://bridge.walletconnect.org",
qrcodeModal: myCustomQRCodeModal
})

**Comment by pedrouid** [comment]
you could override the private field called `_clientMeta` which should match the following structure:

```typescript
 interface IClientMeta {
    description: string;
    url: string;
    icons: string[];
    name: string;
  }

```

**Comment by lgushijima** [comment]
hey Pedro! thanks for helping me on that, but I'm not sure if I got it exactly where to do that... do you have any sample with that?

**Comment by pedrouid** [comment]
example

```js
// instantiate connector
const connector = new WalletConnect({
  bridge: "https://bridge.walletconnect.org",
  qrcodeModal: myCustomQRCodeModal
})
// change client meta
connector. _clientMeta = {
  name: "My App",
  description: "an app that does something",
  url: "https://myappwebsite.com",
  icons: ["https://myappwebsite.com/logo.png"]
  }
  ```

**Comment by lgushijima** [comment]
Thank you very much Pedro!!! 
That did the trick!!  I was trying to send those values inside the constructor!!

** Sorry my delay to answer here, I had to give a time from that, just returned on this today.
