### ISSUE TITLE
Error: ChainId missing or not supported

### ISSUE THREAD

**Issue by ligi** [WalletConnect/walletconnect-example-dapp#62]
The problem is in this state I just get a white-screen and hence also cannot disconnect anymore. Maybe it should automatically disconnect in this case.

![Selection_444](https://user-images.githubusercontent.com/111600/106364690-347bad80-6331-11eb-8351-652f3d54867e.png)

**Comment by critesjosh** [comment]
I am also seeing this error

**Comment by where-design-meets-art** [comment]
Go into Developer Tools -> Application -> Local Storage and remove every `walletconnect` keys you see there.

**Comment by juanudk** [comment]
For me the solutution was open the metamask and change de network, I was trying to run in localhost without network configuration.
