### ISSUE TITLE
correct 'from' for test transaction

### ISSUE THREAD

**Issue by ligi** [WalletConnect/walletconnect-example-dapp#8]
currently I am getting this for a test-transaction:

`{"data":{"id":1542978461535123,"jsonrpc":"2.0","params":[{"from":"0xab12...1cd","to":"0x0","nonce":1,"gas":100000,"value":0,"data":"0x0"}],"method":"eth_sendTransaction"}`

especially the 'from' is problematic and should be the address that was agreed on in the session creation

**Comment by pedrouid** [comment]
Yeah I had a fix for this locally which I forgot to push where I construct a transaction to send to yourself with zero value, I will updated in a second and include the logout fix for issue #7 as well
